# Generated by Django 5.2.5 on 2025-09-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParserRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failure", "Ошибка")],
                        max_length=20,
                    ),
                ),
                ("tasks_count", models.PositiveIntegerField(default=0)),
                ("details", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Запуск парсера",
                "verbose_name_plural": "Запуски парсера",
                "ordering": ["-created_at"],
            },
        ),
    ]
