# Generated by Django 5.2.5 on 2025-09-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("contact_name", models.CharField(max_length=255)),
                (
                    "student_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grade", models.PositiveSmallIntegerField()),
                ("contact_info", models.TextField()),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[("individual", "Individual"), ("group", "Group")],
                        max_length=10,
                    ),
                ),
                (
                    "source_offer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("processed", "Processed")],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        related_name="applications", to="applications.subject"
                    ),
                ),
            ],
        ),
    ]
