# Generated by Django 5.2.5 on 2025-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="grade",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="applications", to="subjects.subject"
            ),
        ),
    ]
