# Generated by Django 5.2.5 on 2025-09-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_application_grade_alter_application_subjects"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="lesson_type",
            field=models.CharField(default="placeholder", max_length=50),
        ),
    ]
