# Generated by Django 5.2.5 on 2025-09-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_application_lesson_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="lesson_type",
            field=models.CharField(default="pass", max_length=50),
        ),
    ]
