# Generated by Django 5.2.5 on 2025-09-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("recsys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="exam_versions",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="recsys.examversion"
            ),
        ),
    ]
