# Generated by Django 5.2.5 on 2025-10-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_methodist_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='classstudentmembership',
            new_name='accounts_cl_study_c_8737b3_idx',
            old_name='accounts_class_student_idx',
        ),
        migrations.RenameIndex(
            model_name='classstudentmembership',
            new_name='accounts_cl_student_aff440_idx',
            old_name='accounts_class_student_only_idx',
        ),
        migrations.RenameIndex(
            model_name='classteachersubject',
            new_name='accounts_cl_study_c_0fa448_idx',
            old_name='accounts_class_teacher_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='classteachersubject',
            new_name='accounts_cl_teacher_beeaf1_idx',
            old_name='accounts_teacher_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='studyclass',
            new_name='accounts_st_join_co_63761e_idx',
            old_name='accounts_studyclass_join_code_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherstudentlink',
            new_name='accounts_te_teacher_f4cd51_idx',
            old_name='accounts_teacher_student_subject_idx',
        ),
        migrations.RenameIndex(
            model_name='teacherstudentlink',
            new_name='accounts_te_invite__38c52a_idx',
            old_name='accounts_teacher_student_code_idx',
        ),
        migrations.RenameIndex(
            model_name='teachersubjectinvite',
            new_name='accounts_te_teacher_f1c9a4_idx',
            old_name='accounts_invite_teacher_subject_idx',
        ),
    ]
