# Generated by Django 5.2.9 on 2026-08-28 09:47

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_preferences(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    UserPreferences = apps.get_model('accounts', 'UserPreferences')
    UserPreferences.objects.bulk_create(
        [UserPreferences(user_id=user_id) for user_id in User.objects.values_list('id', flat=True)],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_class_student_idx_accounts_cl_study_c_8737b3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, validators=[accounts.models.validate_timezone_name])),
                ('city', models.CharField(blank=True, max_length=120)),
                ('timezone_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User preferences',
                'verbose_name_plural': 'User preferences',
            },
        ),
        migrations.RunPython(create_user_preferences, migrations.RunPython.noop),
    ]
