# Generated by Django 5.2.5 on 2025-09-26 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_coursemodule_coursetheorycard_coursemoduleitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preset_name", models.CharField(blank=True, max_length=100)),
                ("row_h", models.PositiveIntegerField(default=60)),
                ("col_w", models.PositiveIntegerField(default=60)),
                ("margin_x", models.PositiveIntegerField(default=24)),
                ("margin_y", models.PositiveIntegerField(default=24)),
                ("node_r", models.PositiveIntegerField(default=24)),
                ("breakpoints", models.JSONField(default=dict)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course layout",
                "verbose_name_plural": "Course layouts",
            },
        ),
        migrations.CreateModel(
            name="CourseGraphEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(blank=True, max_length=50)),
                (
                    "weight",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="graph_edges",
                        to="courses.course",
                    ),
                ),
                (
                    "dst",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_edges",
                        to="courses.coursemodule",
                    ),
                ),
                (
                    "src",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_edges",
                        to="courses.coursemodule",
                    ),
                ),
            ],
            options={
                "ordering": ("course", "src_id", "dst_id"),
                "indexes": [
                    models.Index(
                        fields=["course", "src"], name="courses_edge_course_src"
                    ),
                    models.Index(
                        fields=["course", "dst"], name="courses_edge_course_dst"
                    ),
                ],
            },
        ),
    ]
