# Generated by Django 5.2.5 on 2025-09-26 07:38

from copy import deepcopy

from django.db import migrations


DEFAULT_BREAKPOINTS = {
    "lg": {"columns": 12, "rowHeight": 60},
    "md": {"columns": 8, "rowHeight": 60},
    "sm": {"columns": 4, "rowHeight": 60},
}


def create_layouts_and_edges(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    CourseLayout = apps.get_model("courses", "CourseLayout")
    CourseModule = apps.get_model("courses", "CourseModule")
    CourseGraphEdge = apps.get_model("courses", "CourseGraphEdge")

    for course in Course.objects.all():
        CourseLayout.objects.get_or_create(
            course=course,
            defaults={
                "preset_name": "default",
                "row_h": 60,
                "col_w": 60,
                "margin_x": 24,
                "margin_y": 24,
                "node_r": 24,
                "breakpoints": deepcopy(DEFAULT_BREAKPOINTS),
            },
        )

        modules = CourseModule.objects.filter(course=course).order_by("rank", "col", "pk")
        previous_module = None
        for module in modules:
            if previous_module:
                CourseGraphEdge.objects.get_or_create(
                    course=course,
                    src=previous_module,
                    dst=module,
                    defaults={"kind": "sequential", "weight": 1, "is_locked": False},
                )
            previous_module = module


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_courselayout_coursegraphedge"),
    ]

    operations = [migrations.RunPython(create_layouts_and_edges, noop)]
