# Generated by Django 5.2.5 on 2025-09-06 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subjects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_versions",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "exam_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_groups",
                        to="recsys.examversion",
                    ),
                ),
            ],
            options={
                "ordering": ["exam_version", "id"],
            },
        ),
        migrations.CreateModel(
            name="SkillGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recsys.skillgroup",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_items",
                        to="recsys.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SkillMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mastery", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="recsys.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_masteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "exam_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="recsys.examversion",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="subjects.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="recsys.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("attempts_count", models.PositiveIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="recsys.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.FloatField(default=1.0)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recsys.skill"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recsys.task"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="skills",
            field=models.ManyToManyField(
                related_name="tasks", through="recsys.TaskSkill", to="recsys.skill"
            ),
        ),
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_types",
                        to="subjects.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="recsys.tasktype",
            ),
        ),
        migrations.CreateModel(
            name="TypeMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mastery", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "task_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="recsys.tasktype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_masteries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="examversion",
            index=models.Index(
                fields=["subject", "name"], name="recsys_exam_subject_12abc7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examversion",
            unique_together={("subject", "name")},
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["subject", "name"], name="recsys_skil_subject_6aeda0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("subject", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="skillgroup",
            unique_together={("exam_version", "title")},
        ),
        migrations.AddIndex(
            model_name="skillgroupitem",
            index=models.Index(fields=["group"], name="recsys_skil_group_i_e9347a_idx"),
        ),
        migrations.AddIndex(
            model_name="skillgroupitem",
            index=models.Index(fields=["skill"], name="recsys_skil_skill_i_09a9d8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="skillgroupitem",
            unique_together={("group", "skill")},
        ),
        migrations.AddIndex(
            model_name="skillmastery",
            index=models.Index(
                fields=["user", "skill"], name="recsys_skil_user_id_e95db1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="skillmastery",
            unique_together={("user", "skill")},
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["user", "task"], name="recsys_reco_user_id_4c2c85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["user", "task"], name="recsys_atte_user_id_91d275_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskskill",
            index=models.Index(fields=["task"], name="recsys_task_task_id_d695f8_idx"),
        ),
        migrations.AddIndex(
            model_name="taskskill",
            index=models.Index(fields=["skill"], name="recsys_task_skill_i_139754_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="taskskill",
            unique_together={("task", "skill")},
        ),
        migrations.AddIndex(
            model_name="tasktype",
            index=models.Index(
                fields=["subject", "name"], name="recsys_task_subject_ebf2f0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tasktype",
            unique_together={("subject", "name")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["subject", "exam_version", "type", "title"],
                name="recsys_task_subject_506513_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("subject", "exam_version", "type", "title")},
        ),
        migrations.AddIndex(
            model_name="typemastery",
            index=models.Index(
                fields=["user", "task_type"], name="recsys_type_user_id_57e973_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="typemastery",
            unique_together={("user", "task_type")},
        ),
    ]
