# Generated by Django 5.2.5 on 2025-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="correct_answer",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="difficulty",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="preliminary_difficulty",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="statement_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="task_statements/"
            ),
        ),
    ]
