# Generated by Django 5.2.5 on 2025-09-20 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VariantAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VariantAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent", models.DurationField(blank=True, null=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="recsys.variantassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["assignment", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="VariantTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField()),
                ("max_attempts", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_tasks",
                        to="recsys.task",
                    ),
                ),
            ],
            options={
                "ordering": ["template", "order"],
            },
        ),
        migrations.CreateModel(
            name="VariantTaskAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveIntegerField(default=1)),
                ("is_correct", models.BooleanField(default=False)),
                ("task_snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="variant_task_attempts",
                        to="recsys.task",
                    ),
                ),
                (
                    "variant_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_attempts",
                        to="recsys.variantattempt",
                    ),
                ),
                (
                    "variant_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_attempts",
                        to="recsys.varianttask",
                    ),
                ),
            ],
            options={
                "ordering": ["variant_attempt", "variant_task", "attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="VariantTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("time_limit", models.DurationField(blank=True, null=True)),
                ("max_attempts", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="variant_templates",
                        through="recsys.VariantTask",
                        to="recsys.task",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="varianttask",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_tasks",
                to="recsys.varianttemplate",
            ),
        ),
        migrations.AddField(
            model_name="variantassignment",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="recsys.varianttemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="variantattempt",
            index=models.Index(
                fields=["assignment", "attempt_number"],
                name="recsys_vari_assignm_d00f7f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="variantattempt",
            index=models.Index(
                fields=["assignment"], name="recsys_vari_assignm_3fb62c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="variantattempt",
            unique_together={("assignment", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="varianttaskattempt",
            index=models.Index(
                fields=["variant_attempt"], name="recsys_vari_variant_4dc719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="varianttaskattempt",
            index=models.Index(
                fields=["variant_task"], name="recsys_vari_variant_4d71e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="varianttaskattempt",
            unique_together={("variant_attempt", "variant_task", "attempt_number")},
        ),
        migrations.AddIndex(
            model_name="varianttemplate",
            index=models.Index(fields=["name"], name="recsys_vari_name_4f23f7_idx"),
        ),
        migrations.AddIndex(
            model_name="varianttask",
            index=models.Index(
                fields=["template", "order"], name="recsys_vari_templat_0c0b94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="varianttask",
            index=models.Index(
                fields=["template", "task"], name="recsys_vari_templat_c2c65e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="varianttask",
            unique_together={("template", "order"), ("template", "task")},
        ),
        migrations.AddIndex(
            model_name="variantassignment",
            index=models.Index(fields=["user"], name="recsys_vari_user_id_0b1946_idx"),
        ),
        migrations.AddIndex(
            model_name="variantassignment",
            index=models.Index(
                fields=["template"], name="recsys_vari_templat_11391d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="variantassignment",
            index=models.Index(
                fields=["user", "template"], name="recsys_vari_user_id_09fa28_idx"
            ),
        ),
    ]
