# Generated by Django 5.2.5 on 2025-09-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="attempts_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
