# Generated by Django 5.2.5 on 2025-09-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0001_initial"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tasktype",
            name="recsys_task_subject_ebf2f0_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tasktype",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="exam_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_types",
                to="recsys.examversion",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tasktype",
            unique_together={("subject", "exam_version", "name")},
        ),
        migrations.AddIndex(
            model_name="tasktype",
            index=models.Index(
                fields=["subject", "exam_version", "name"],
                name="recsys_task_subject_647945_idx",
            ),
        ),
    ]
