# Generated by Django 5.2.5 on 2025-09-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillmastery",
            name="confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="typemastery",
            name="confidence",
            field=models.FloatField(default=0.0),
        ),
    ]
