# Generated by Django 5.2.5 on 2025-09-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0002_attempt_attempts_count"),
        ("recsys", "0002_skillmastery_confidence_typemastery_confidence"),
    ]

    operations = []
