# Generated by Django 5.2.5 on 2025-09-20 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0002_variantassignment_variantattempt_varianttask_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="variant_task_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="recsys.varianttaskattempt",
            ),
        ),
        migrations.AddField(
            model_name="attempt",
            name="weight",
            field=models.FloatField(default=1.0),
        ),
    ]
