# Generated by Django 5.2.5 on 2025-09-03 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0003_merge_20250901_2151"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exam_type", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="skill",
            name="exam_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="recsys.examversion",
            ),
        ),
        migrations.AddField(
            model_name="tasktype",
            name="exam_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_types",
                to="recsys.examversion",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="recsys_subj_name_194e06_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="examversion",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_versions",
                to="recsys.subject",
            ),
        ),
        migrations.AddIndex(
            model_name="examversion",
            index=models.Index(
                fields=["subject", "exam_type", "year"],
                name="recsys_exam_subject_015483_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examversion",
            unique_together={("subject", "exam_type", "year")},
        ),
    ]
