# Generated by Django 5.2.5 on 2025-09-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0003_attempt_variant_task_attempt_attempt_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="default_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="generator_slug",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="task",
            name="is_dynamic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="rendering_strategy",
            field=models.CharField(
                choices=[
                    ("plain", "Plain text"),
                    ("markdown", "Markdown"),
                    ("html", "HTML"),
                ],
                default="markdown",
                max_length=32,
            ),
        ),
    ]
