# Generated by Django 5.2.5 on 2025-09-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recsys",
            "0004_examversion_skill_exam_version_tasktype_exam_version_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["exam_version"], name="recsys_skil_exam_ve_d07321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tasktype",
            index=models.Index(
                fields=["exam_version"], name="recsys_task_exam_ve_ed534e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exam_version__isnull", False)),
                fields=("exam_version", "name"),
                name="recsys_skill_exam_version_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasktype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exam_version__isnull", False)),
                fields=("exam_version", "name"),
                name="recsys_tasktype_exam_version_name_unique",
            ),
        ),
    ]
