# Generated by Django 5.2.5 on 2025-09-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0004_task_default_payload_task_generator_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasktype",
            name="exam_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_types",
                to="recsys.examversion",
            ),
        ),
    ]
