# Generated by Django 5.2.5 on 2025-09-03 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0004_subject_skill_subject_tasktype_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="recsys_exam_name_f371c3_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "exam_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_groups",
                        to="recsys.examversion",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SkillGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="recsys.skillgroup",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recsys.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="skillgroup",
            index=models.Index(
                fields=["exam_version", "title"], name="recsys_skil_exam_ve_f0bc11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skillgroupitem",
            index=models.Index(fields=["group"], name="recsys_skil_group_i_e9347a_idx"),
        ),
        migrations.AddIndex(
            model_name="skillgroupitem",
            index=models.Index(fields=["skill"], name="recsys_skil_skill_i_09a9d8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="skillgroupitem",
            unique_together={("group", "skill")},
        ),
    ]
