# Generated by Django 5.2.5 on 2025-09-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0004_examversion_skillgroup_skillgroupitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveIndex(
            model_name="skill",
            name="recsys_skil_name_e50b05_idx",
        ),
        migrations.RemoveIndex(
            model_name="task",
            name="recsys_task_type_id_c7eaf4_idx",
        ),
        migrations.RemoveIndex(
            model_name="tasktype",
            name="recsys_task_name_bb4c10_idx",
        ),
        migrations.AddField(
            model_name="task",
            name="exam_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="recsys.examversion",
            ),
        ),
        migrations.AlterField(
            model_name="examversion",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["name"], name="recsys_subj_name_194e06_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="examversion",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_versions",
                to="recsys.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="recsys.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="recsys.subject",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tasktype",
            name="subject",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_types",
                to="recsys.subject",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="examversion",
            unique_together={("subject", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together={("subject", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("subject", "exam_version", "type", "title")},
        ),
        migrations.AlterUniqueTogether(
            name="tasktype",
            unique_together={("subject", "name")},
        ),
        migrations.AddIndex(
            model_name="examversion",
            index=models.Index(
                fields=["subject", "name"], name="recsys_exam_subject_12abc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["subject", "name"], name="recsys_skil_subject_6aeda0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["subject", "exam_version", "type", "title"],
                name="recsys_task_subject_506513_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tasktype",
            index=models.Index(
                fields=["subject", "name"], name="recsys_task_subject_ebf2f0_idx"
            ),
        ),
    ]
