# Generated by Django 5.2.5 on 2025-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0005_tasktype_exam_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="correct_answer",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="task",
            name="difficulty_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="first_attempt_failed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="first_attempt_total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(blank=True, upload_to="tasks/screenshots/"),
        ),
    ]
