# Generated by Django 5.2.5 on 2025-09-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0006_task_correct_answer_task_difficulty_level_and_more"),
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="tasktype",
            name="recsys_task_subject_ebf2f0_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tasktype",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="tasktype",
            index=models.Index(
                fields=["subject", "exam_version", "name"],
                name="recsys_task_subject_647945_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tasktype",
            constraint=models.UniqueConstraint(
                fields=("subject", "exam_version", "name"),
                name="task_type_subject_exam_name_unique",
            ),
        ),
    ]
