# Generated by Django 5.2.5 on 2025-10-23 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0007_remove_tasktype_recsys_task_subject_ebf2f0_idx_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='subjects.subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='recsys.tasktag'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='required_tags',
            field=models.ManyToManyField(blank=True, related_name='required_for_task_types', to='recsys.tasktag'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['subject', 'name'], name='recsys_task_subject_077096_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktag',
            unique_together={('subject', 'name')},
        ),
    ]
