# Generated by Django 5.2.5 on 2025-10-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0009_tasktype_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPreGeneratedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter_values', models.JSONField(blank=True, default=dict)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pre-generated dataset',
                'verbose_name_plural': 'Pre-generated datasets',
                'ordering': ['task', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='tasktype',
            new_name='recsys_task_subject_132f77_idx',
            old_name='recsys_task_subject_d282d1_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='dynamic_mode',
            field=models.CharField(choices=[('generator', 'Generator'), ('pre_generated', 'Pre-generated pool')], default='generator', max_length=32),
        ),
        migrations.AddField(
            model_name='taskpregenerateddataset',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregenerated_datasets', to='recsys.task'),
        ),
        migrations.AddIndex(
            model_name='taskpregenerateddataset',
            index=models.Index(fields=['task', 'is_active'], name='recsys_task_task_id_a9edcb_idx'),
        ),
    ]
