# Generated by Django 5.2.5 on 2025-12-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0011_clamp_negative_mastery'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional override of task-type max score.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='scoring_scheme',
            field=models.CharField(blank=True, choices=[('binary', 'Binary (0/1)'), ('partial_pairs', 'Partial pairs (0-2)'), ('partial_rows', 'Partial rows (0-2)'), ('manual_scaled', 'Manual scaled')], help_text='Optional override of task-type scoring scheme.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum primary points for this task type.'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='scoring_scheme',
            field=models.CharField(choices=[('binary', 'Binary (0/1)'), ('partial_pairs', 'Partial pairs (0-2)'), ('partial_rows', 'Partial rows (0-2)'), ('manual_scaled', 'Manual scaled')], default='binary', help_text='How to award points for answers of this task type.', max_length=32),
        ),
        migrations.AddField(
            model_name='varianttaskattempt',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='varianttaskattempt',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
