# Generated by Django 5.2.5 on 2025-12-19 14:10

import apps.recsys.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0012_task_max_score_task_scoring_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, help_text='Machine-friendly code, e.g. 17-01-krylov', max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('file', 'File'), ('image', 'Image')], default='file', max_length=10)),
                ('file', models.FileField(upload_to=apps.recsys.models.task_attachment_upload_to)),
                ('label', models.CharField(blank=True, help_text='Optional marker like A/B or 01 for multiple files.', max_length=50)),
                ('download_name_override', models.CharField(blank=True, help_text='If set, this name is suggested for download instead of slug-based.', max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='recsys.task')),
            ],
            options={
                'ordering': ['task', 'kind', 'order', 'id'],
                'indexes': [models.Index(fields=['task', 'kind', 'order'], name='recsys_task_task_id_4de567_idx')],
            },
        ),
    ]
