# Generated by Django 5.2.5 on 2025-12-19 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0013_task_slug_taskattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='recsys_sour_name_73d5f6_idx'), models.Index(fields=['slug'], name='recsys_sour_slug_219c3c_idx')],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='recsys.source'),
        ),
        migrations.CreateModel(
            name='SourceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text='Например: дата варианта (13.12.2025) или номер (19).', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='recsys.source')),
            ],
            options={
                'ordering': ['source__name', 'label'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='source_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='recsys.sourcevariant'),
        ),
        migrations.AddIndex(
            model_name='sourcevariant',
            index=models.Index(fields=['source', 'label'], name='recsys_sour_source__289a88_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcevariant',
            index=models.Index(fields=['source', 'slug'], name='recsys_sour_source__ec0f68_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sourcevariant',
            unique_together={('source', 'label')},
        ),
    ]
