# Generated by Django 5.2.5 on 2025-12-24 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0014_source_task_source_sourcevariant_task_source_variant_and_more'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Structure of answer fields (rows/columns, types, validation, optionality) used to render input UI and normalise answers.')),
                ('is_active', models.BooleanField(default=True)),
                ('exam_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_schemas', to='recsys.examversion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_schemas', to='subjects.subject')),
            ],
            options={
                'ordering': ['subject', 'exam_version', 'name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='answer_schema',
            field=models.ForeignKey(blank=True, help_text='Optional override of task-type answer schema (fields per answer).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='recsys.answerschema'),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='answer_schema',
            field=models.ForeignKey(blank=True, help_text='How many answer inputs to show and of what kind (per subject/exam).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_types', to='recsys.answerschema'),
        ),
        migrations.AddIndex(
            model_name='answerschema',
            index=models.Index(fields=['subject', 'exam_version', 'name', 'is_active'], name='recsys_answ_subject_d1c64f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answerschema',
            unique_together={('subject', 'exam_version', 'name')},
        ),
    ]
