# Generated by Django 5.2.5 on 2025-12-24

from django.db import migrations


def _get_subject(apps, name):
    Subject = apps.get_model("subjects", "Subject")
    try:
        return Subject.objects.get(name__iexact=name)
    except Subject.DoesNotExist:
        return None


def _get_exam_version(apps, subject, name):
    ExamVersion = apps.get_model("recsys", "ExamVersion")
    if not subject or not name:
        return None
    try:
        return ExamVersion.objects.get(subject=subject, name__iexact=name)
    except ExamVersion.DoesNotExist:
        return None


def _create_schema(apps, subject, exam_version, name, description, config):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    if not subject:
        return
    AnswerSchema.objects.update_or_create(
        subject=subject,
        exam_version=exam_version,
        name=name,
        defaults={
            "description": description,
            "config": config,
            "is_active": True,
        },
    )


def seed_answer_schemas(apps, schema_editor):
    subject_inf = _get_subject(apps, "Информатика")
    # ЕГЭ Информатика
    inf_exam = _get_exam_version(apps, subject_inf, "Информатика ЕГЭ 2026") or _get_exam_version(apps, subject_inf, "ЕГЭ")

    _create_schema(
        apps,
        subject_inf,
        inf_exam,
        "single_uint",
        "Одно поле, целое без знака",
        {"rows": 1, "cols": 1, "input_type": "uint", "case_insensitive": False},
    )
    _create_schema(
        apps,
        subject_inf,
        inf_exam,
        "single_string_ci",
        "Одно поле, строка, регистр не важен",
        {"rows": 1, "cols": 1, "input_type": "string", "case_insensitive": True},
    )
    _create_schema(
        apps,
        subject_inf,
        inf_exam,
        "double_uint",
        "Два поля, целые без знака",
        {"rows": 1, "cols": 2, "input_type": "uint", "case_insensitive": False},
    )
    _create_schema(
        apps,
        subject_inf,
        inf_exam,
        "grid_2x2_uint",
        "Таблица 2x2, целые без знака",
        {"rows": 2, "cols": 2, "input_type": "uint", "case_insensitive": False},
    )
    _create_schema(
        apps,
        subject_inf,
        inf_exam,
        "grid_10x2_uint",
        "Таблица 10x2, целые без знака",
        {
            "rows": 10,
            "cols": 2,
            "input_type": "uint",
            "case_insensitive": False,
            "allow_blank_rows": True,
        },
    )

    # Универсальные схемы для остальных предметов
    subject_generic = None  # will apply to any subject as needed manually
    test_config = {
        "rows": 1,
        "cols": 17,
        "input_type": "char",
        "per_cell_max_length": 1,
        "auto_advance": True,
        "backspace": "previous_cell",
    }
    manual_config = {
        "rows": 1,
        "cols": 1,
        "input_type": "text",
        "manual_check": True,
        "ui_hint": "textarea",
    }
    # If there is a generic subject named "Общий" or similar, attach; otherwise leave unattached.
    for candidate in ["Общий", "Общие", "Все предметы", "General", "Common"]:
        subject_generic = subject_generic or _get_subject(apps, candidate)
    if subject_generic:
        _create_schema(
            apps,
            subject_generic,
            None,
            "test_part_17_cells",
            "17 клеток по 1 символу, автопереход вправо",
            test_config,
        )
        _create_schema(
            apps,
            subject_generic,
            None,
            "free_form_manual",
            "Свободный ответ, ручная проверка",
            manual_config,
        )


def unseed_answer_schemas(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    AnswerSchema.objects.filter(
        name__in=[
            "single_uint",
            "single_string_ci",
            "double_uint",
            "grid_2x2_uint",
            "grid_10x2_uint",
            "test_part_17_cells",
            "free_form_manual",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0015_answerschema_task_answer_schema_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_answer_schemas, reverse_code=unseed_answer_schemas),
    ]
