# Generated by ChatGPT on 2025-12-30
from django.db import migrations


def _get_subject(apps, name):
    Subject = apps.get_model("subjects", "Subject")
    try:
        return Subject.objects.get(name__iexact=name)
    except Subject.DoesNotExist:
        return None


def _get_exam_version(apps, subject, name):
    ExamVersion = apps.get_model("recsys", "ExamVersion")
    if not subject or not name:
        return None
    try:
        return ExamVersion.objects.get(subject=subject, name__iexact=name)
    except ExamVersion.DoesNotExist:
        return None


def add_answer_schema(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    subject = _get_subject(apps, "Информатика")
    exam_version = _get_exam_version(apps, subject, "Информатика ЕГЭ 2026")
    if not subject or not exam_version:
        return
    AnswerSchema.objects.update_or_create(
        subject=subject,
        exam_version=exam_version,
        name="test_part_17_chars",
        defaults={
            "description": "17 клеток, по 1 символу, автопереход курсора",
            "config": {
                "rows": 1,
                "cols": 17,
                "input_type": "char",
                "per_cell_max_length": 1,
                "auto_advance": True,
                "backspace": "previous_cell",
            },
            "is_active": True,
        },
    )


def remove_answer_schema(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    AnswerSchema.objects.filter(name="test_part_17_chars").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0016_seed_answer_schemas"),
    ]

    operations = [
        migrations.RunPython(add_answer_schema, reverse_code=remove_answer_schema),
    ]
