# Generated by ChatGPT on 2025-12-30
from django.db import migrations


def _get_subject(apps, name):
    Subject = apps.get_model("subjects", "Subject")
    try:
        return Subject.objects.get(name__iexact=name)
    except Subject.DoesNotExist:
        return None


def _get_exam_version(apps, subject, name):
    ExamVersion = apps.get_model("recsys", "ExamVersion")
    if not subject or not name:
        return None
    try:
        return ExamVersion.objects.get(subject=subject, name__iexact=name)
    except ExamVersion.DoesNotExist:
        return None


def add_answer_schema(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    subject = _get_subject(apps, "Информатика")
    exam_version = _get_exam_version(apps, subject, "Информатика ЕГЭ 2026")
    if not subject or not exam_version:
        return
    AnswerSchema.objects.update_or_create(
        subject=subject,
        exam_version=exam_version,
        name="free_form_long",
        defaults={
            "description": "Свободный развернутый ответ (текстовое поле)",
            "config": {
                "rows": 1,
                "cols": 1,
                "input_type": "text",
                "ui_hint": "textarea",
                "manual_check": True,
            },
            "is_active": True,
        },
    )


def remove_answer_schema(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    AnswerSchema.objects.filter(name="free_form_long").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0017_add_answer_schema_test_part_17_chars"),
    ]

    operations = [
        migrations.RunPython(add_answer_schema, reverse_code=remove_answer_schema),
    ]
