# Generated by ChatGPT on 2025-12-30
from django.db import migrations


TEST_SCHEMA_NAME = "test_part_17_chars"
FREE_SCHEMA_NAME = "free_form_long"


def create_generic_schemas(apps, schema_editor):
    Subject = apps.get_model("subjects", "Subject")
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")

    subjects = Subject.objects.exclude(name__iexact="Информатика")
    for subj in subjects:
        AnswerSchema.objects.update_or_create(
            subject=subj,
            exam_version=None,
            name=TEST_SCHEMA_NAME,
            defaults={
                "description": "17 клеток, по 1 символу, автопереход курсора",
                "config": {
                    "rows": 1,
                    "cols": 17,
                    "input_type": "char",
                    "per_cell_max_length": 1,
                    "auto_advance": True,
                    "backspace": "previous_cell",
                },
                "is_active": True,
            },
        )
        AnswerSchema.objects.update_or_create(
            subject=subj,
            exam_version=None,
            name=FREE_SCHEMA_NAME,
            defaults={
                "description": "Свободный развернутый ответ (текстовое поле)",
                "config": {
                    "rows": 1,
                    "cols": 1,
                    "input_type": "text",
                    "ui_hint": "textarea",
                    "manual_check": True,
                },
                "is_active": True,
            },
        )

    # удалить старые привязки к информатике
    AnswerSchema.objects.filter(
        subject__name__iexact="Информатика",
        name__in=[TEST_SCHEMA_NAME, FREE_SCHEMA_NAME],
    ).delete()


def remove_generic_schemas(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    AnswerSchema.objects.filter(
        name__in=[TEST_SCHEMA_NAME, FREE_SCHEMA_NAME]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0018_add_answer_schema_free_form_long"),
    ]

    operations = [
        migrations.RunPython(create_generic_schemas, reverse_code=remove_generic_schemas),
    ]
