# Generated by Django 5.2.5 on 2026-01-11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0020_tasktype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="variantattempt",
            name="active_started_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text="Timestamp when the current task timer was started.",
            ),
        ),
        migrations.AddField(
            model_name="variantattempt",
            name="active_variant_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Variant task currently opened by the student (for per-task timers).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="recsys.varianttask",
            ),
        ),
        migrations.AddField(
            model_name="varianttaskattempt",
            name="time_spent",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="VariantTaskTimeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField()),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "stop_reason",
                    models.CharField(
                        choices=[
                            ("switch", "Switched to another task"),
                            ("save", "Answer saved"),
                            ("submit", "Answer submitted"),
                            ("finalize", "Attempt finalized"),
                            ("clear", "Answer cleared"),
                            ("auto", "Auto stop"),
                        ],
                        default="switch",
                        max_length=16,
                    ),
                ),
                ("auto_stopped", models.BooleanField(default=False)),
                (
                    "variant_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="time_logs", to="recsys.variantattempt"
                    ),
                ),
                (
                    "variant_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="time_logs", to="recsys.varianttask"
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="varianttasktimelog",
            index=models.Index(fields=["variant_attempt", "variant_task", "stopped_at"], name="recsys_var_variant_081fa0_idx"),
        ),
        migrations.AddIndex(
            model_name="varianttasktimelog",
            index=models.Index(fields=["variant_attempt", "stopped_at"], name="recsys_var_variant_10dd5b_idx"),
        ),
    ]
