# Generated by Django 5.2.5 on 2026-01-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0021_varianttasktimelog_and_timing_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='varianttasktimelog',
            new_name='recsys_vari_variant_cff3a1_idx',
            old_name='recsys_var_variant_081fa0_idx',
        ),
        migrations.RenameIndex(
            model_name='varianttasktimelog',
            new_name='recsys_vari_variant_54f585_idx',
            old_name='recsys_var_variant_10dd5b_idx',
        ),
    ]
