# Generated by Django 5.2.5 on 2026-01-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0027_exam_score_scale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examversion',
            options={'ordering': ['subject__name', 'name']},
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS recsys_examb_exam_vers_0a3a9e_idx "
                "RENAME TO recsys_exam_exam_ve_720af5_idx;",
            reverse_sql="ALTER INDEX IF EXISTS recsys_exam_exam_ve_720af5_idx "
                        "RENAME TO recsys_examb_exam_vers_0a3a9e_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS recsys_examb_bluepri_3c6497_idx "
                "RENAME TO recsys_exam_bluepri_fd61a1_idx;",
            reverse_sql="ALTER INDEX IF EXISTS recsys_exam_bluepri_fd61a1_idx "
                        "RENAME TO recsys_examb_bluepri_3c6497_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS recsys_exam_subject_name_idx "
                "RENAME TO recsys_exam_subject_12abc7_idx;",
            reverse_sql="ALTER INDEX IF EXISTS recsys_exam_subject_12abc7_idx "
                        "RENAME TO recsys_exam_subject_name_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS recsys_exam_slug_idx "
                "RENAME TO recsys_exam_slug_70e8d0_idx;",
            reverse_sql="ALTER INDEX IF EXISTS recsys_exam_slug_70e8d0_idx "
                        "RENAME TO recsys_exam_slug_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS recsys_exam_status_idx "
                "RENAME TO recsys_exam_status_c17481_idx;",
            reverse_sql="ALTER INDEX IF EXISTS recsys_exam_status_c17481_idx "
                        "RENAME TO recsys_exam_status_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS recsys_var_sl_a2f963_idx "
                "RENAME TO recsys_vari_slug_feadc9_idx;",
            reverse_sql="ALTER INDEX IF EXISTS recsys_vari_slug_feadc9_idx "
                        "RENAME TO recsys_var_sl_a2f963_idx;",
        ),
        migrations.RunSQL(
            sql="ALTER INDEX IF EXISTS recsys_varia_exam_ve_1b4795_idx "
                "RENAME TO recsys_vari_exam_ve_a77626_idx;",
            reverse_sql="ALTER INDEX IF EXISTS recsys_vari_exam_ve_a77626_idx "
                        "RENAME TO recsys_varia_exam_ve_1b4795_idx;",
        ),
        migrations.AlterField(
            model_name='varianttasktimelog',
            name='stop_reason',
            field=models.CharField(choices=[('switch', 'Switched to another task'), ('save', 'Answer saved'), ('submit', 'Answer submitted'), ('finalize', 'Attempt finalized'), ('clear', 'Answer cleared'), ('attempt_timeout', 'Attempt time limit reached'), ('auto', 'Auto stop')], default='switch', max_length=16),
        ),
    ]
