# Generated by Codex on 2026-01-08

from django.db import migrations, models


def allow_blank_rows_for_grid_10x2(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    for schema in AnswerSchema.objects.filter(name="grid_10x2_uint"):
        config = schema.config or {}
        if not isinstance(config, dict):
            config = {}
        if config.get("allow_blank_rows") is True:
            continue
        config["allow_blank_rows"] = True
        schema.config = config
        schema.save(update_fields=["config"])


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0029_examversion_start_info"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="answerschema",
            name="recsys_answ_subject_d1c64f_idx",
        ),
        migrations.AlterUniqueTogether(
            name="answerschema",
            unique_together={("exam_version", "name")},
        ),
        migrations.RemoveField(
            model_name="answerschema",
            name="subject",
        ),
        migrations.AlterModelOptions(
            name="answerschema",
            options={"ordering": ["exam_version", "name"]},
        ),
        migrations.AddIndex(
            model_name="answerschema",
            index=models.Index(
                fields=["exam_version", "name", "is_active"],
                name="recsys_answ_exam_name_act",
            ),
        ),
        migrations.RunPython(
            allow_blank_rows_for_grid_10x2,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
