# Generated by Codex on 2026-01-08

from django.db import migrations, models


def allow_blank_rows_for_grid_10x2(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    for schema in AnswerSchema.objects.filter(name="grid_10x2_uint"):
        config = schema.config or {}
        if not isinstance(config, dict):
            config = {}
        if config.get("allow_blank_rows") is True:
            continue
        config["allow_blank_rows"] = True
        schema.config = config
        schema.save(update_fields=["config"])


def dedupe_answer_schema_names(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    seen = {}
    duplicates = []
    for schema in AnswerSchema.objects.order_by("id"):
        key = schema.name
        if key in seen:
            duplicates.append(schema.id)
        else:
            seen[key] = schema.id
    if duplicates:
        AnswerSchema.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0030_detach_answerschema_subject_and_allow_blank_rows"),
    ]

    operations = [
        migrations.RunPython(
            allow_blank_rows_for_grid_10x2,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            dedupe_answer_schema_names,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
