# Generated by Codex on 2026-01-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0031_detach_answerschema_exam_and_allow_blank_rows"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="answerschema",
            name="recsys_answ_exam_name_act",
        ),
        migrations.AlterUniqueTogether(
            name="answerschema",
            unique_together={("name",)},
        ),
        migrations.RemoveField(
            model_name="answerschema",
            name="exam_version",
        ),
        migrations.AlterModelOptions(
            name="answerschema",
            options={"ordering": ["name"]},
        ),
        migrations.AddIndex(
            model_name="answerschema",
            index=models.Index(
                fields=["name", "is_active"],
                name="recsys_answ_name_active",
            ),
        ),
    ]
