# Generated by ChatGPT on 2026-01-14
from django.db import migrations


def allow_blank_cells_for_test_part_17_chars(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    for schema in AnswerSchema.objects.filter(name="test_part_17_chars"):
        config = schema.config or {}
        if config.get("allow_blank_cells") is True:
            continue
        config["allow_blank_cells"] = True
        schema.config = config
        schema.save(update_fields=["config"])


def remove_allow_blank_cells_for_test_part_17_chars(apps, schema_editor):
    AnswerSchema = apps.get_model("recsys", "AnswerSchema")
    for schema in AnswerSchema.objects.filter(name="test_part_17_chars"):
        config = schema.config or {}
        if "allow_blank_cells" not in config:
            continue
        config.pop("allow_blank_cells", None)
        schema.config = config
        schema.save(update_fields=["config"])


class Migration(migrations.Migration):

    dependencies = [
        ("recsys", "0033_task_status"),
    ]

    operations = [
        migrations.RunPython(
            allow_blank_cells_for_test_part_17_chars,
            reverse_code=remove_allow_blank_cells_for_test_part_17_chars,
        ),
    ]
