# Generated by Django 5.2.9 on 2026-02-08 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0034_allow_blank_cells_for_test_part_17_chars'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='exam_version',
            field=models.ForeignKey(blank=True, help_text='Optional exam binding for this source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='recsys.examversion'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['exam_version', 'name'], name='recsys_sour_exam_ve_d32dea_idx'),
        ),
    ]
