# Generated by Django 5.2.9 on 2026-03-16 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0035_rename_recsys_examb_exam_vers_0a3a9e_idx_recsys_exam_exam_ve_720af5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mastery', models.FloatField(default=0.0)),
                ('coverage', models.FloatField(default=0.0)),
                ('progress', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('stability', models.FloatField(default=0.0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_total', models.PositiveIntegerField(default=0)),
                ('successes_total', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='attempt_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attempt',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_valid_attempt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='attempt',
            name='mode',
            field=models.CharField(choices=[('training', 'Training'), ('variant', 'Variant')], default='training', max_length=16),
        ),
        migrations.AddField(
            model_name='attempt',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempts', to='recsys.recommendationlog'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='time_spent',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_logs', to='recsys.attempt'),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='rank_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='recommended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='source_mode',
            field=models.CharField(choices=[('training', 'Training'), ('variant', 'Variant'), ('batch', 'Batch'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='status',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('opened', 'Opened'), ('attempted', 'Attempted'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='recommended', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='attempts_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty_empirical',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='level_band',
            field=models.CharField(choices=[('intro', 'Intro'), ('basic', 'Basic'), ('exam', 'Exam'), ('hard', 'Hard')], default='exam', max_length=16),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_manual',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='task',
            name='score_norm_sum_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='typemastery',
            name='attempts_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='typemastery',
            name='coverage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='typemastery',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typemastery',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typemastery',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='typemastery',
            name='stability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='typemastery',
            name='successes_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='varianttaskattempt',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='varianttaskattempt',
            name='is_valid_attempt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tagmastery',
            name='task_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masteries', to='recsys.tasktag'),
        ),
        migrations.AddField(
            model_name='tagmastery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_masteries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tagmastery',
            index=models.Index(fields=['user', 'task_tag'], name='recsys_tagm_user_id_74610c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tagmastery',
            unique_together={('user', 'task_tag')},
        ),
    ]
