# Generated by Django 5.2.9 on 2026-03-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0038_repair_examversion_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='coverage_gain_snapshot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='reason_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='score_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='spacing_gain_snapshot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationlog',
            name='weak_tags_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
