# Generated by Django 5.2.9 on 2026-04-08 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0039_recommendationlog_coverage_gain_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('steps_total', models.PositiveIntegerField(default=0)),
                ('completed_steps', models.PositiveIntegerField(default=0)),
                ('correct_steps', models.PositiveIntegerField(default=0)),
                ('exam_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='recsys.examversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('opened', 'Opened'), ('answered', 'Answered'), ('skipped', 'Skipped')], default='recommended', max_length=16)),
                ('result', models.CharField(choices=[('correct', 'Correct'), ('incorrect', 'Incorrect'), ('partial', 'Partial'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('task_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason_snapshot', models.JSONField(blank=True, default=dict)),
                ('shown_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_session_steps', to='recsys.attempt')),
                ('recommendation_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_steps', to='recsys.recommendationlog')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recsys.trainingsession')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_steps', to='recsys.task')),
            ],
            options={
                'ordering': ['session', 'order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'exam_version', 'status'], name='recsys_trai_user_id_251025_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsession',
            index=models.Index(fields=['user', 'status'], name='recsys_trai_user_id_13f429_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionstep',
            index=models.Index(fields=['session', 'order'], name='recsys_trai_session_616d91_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionstep',
            index=models.Index(fields=['task'], name='recsys_trai_task_id_1ab976_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingsessionstep',
            index=models.Index(fields=['recommendation_log'], name='recsys_trai_recomme_f42095_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingsessionstep',
            unique_together={('session', 'order')},
        ),
    ]
