# Generated by Django 5.2.9 on 2026-09-12 01:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0042_task_time_aggregates'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamProgressSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now)),
                ('algorithm_version', models.CharField(default='exam-progress-v1', max_length=64)),
                ('purpose', models.CharField(default='archive', max_length=32)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-as_of', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TaskPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Доступно'), ('retired', 'Исключено из выдачи')], default='active', max_length=16)),
                ('scoring_scheme', models.CharField(blank=True, choices=[('binary', 'Binary (0/1)'), ('partial_pairs', 'Partial pairs (0-2)'), ('partial_rows', 'Partial rows (0-2)'), ('manual_scaled', 'Manual scaled')], max_length=32)),
                ('max_score', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTypeTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('equivalent', 'Соответствует'), ('partial', 'Частично'), ('split', 'Разделение'), ('merge', 'Объединение'), ('added', 'Новый тип'), ('removed', 'Исключённый тип')], default='equivalent', max_length=16)),
                ('approved', models.BooleanField(default=False)),
                ('task_ids', models.JSONField(blank=True, default=list, help_text='Явный набор задач для частичного соответствия.')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='context_origin',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='attempt',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='exam_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attempts', to='recsys.examversion'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='response_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='task_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attempt',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_attempts', to='recsys.tasktype'),
        ),
        migrations.AddField(
            model_name='examversion',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='recsys.examversion'),
        ),
        migrations.AddField(
            model_name='examversion',
            name='exam_kind',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='examversion',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examversion',
            name='publication_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examversion',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='examversion',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tagmastery',
            name='decayed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variantattempt',
            name='exam_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='recsys.task'),
        ),
        migrations.AlterField(
            model_name='examversion',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Архив')], db_index=True, default='draft', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='examversion',
            constraint=models.UniqueConstraint(fields=('subject', 'exam_kind', 'year', 'revision'), name='exam_year_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='examversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('subject', 'exam_kind'), name='exam_default_unique'),
        ),
        migrations.AddField(
            model_name='examprogresssnapshot',
            name='exam_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_snapshots', to='recsys.examversion'),
        ),
        migrations.AddField(
            model_name='examprogresssnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_progress_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskplacement',
            name='answer_schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recsys.answerschema'),
        ),
        migrations.AddField(
            model_name='taskplacement',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='recsys.task'),
        ),
        migrations.AddField(
            model_name='taskplacement',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='recsys.tasktype'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='recsys.taskplacement'),
        ),
        migrations.AddField(
            model_name='trainingsessionstep',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_steps', to='recsys.taskplacement'),
        ),
        migrations.AddField(
            model_name='varianttask',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_tasks', to='recsys.taskplacement'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['user', 'exam_version', 'task_type', 'created_at'], name='attempt_exam_history_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('user', 'submission_key'), name='attempt_submission_unique'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(condition=models.Q(('context_origin', 'issued'), ('variant_task_attempt__isnull', False)), fields=('variant_task_attempt',), name='attempt_variant_answer_unique'),
        ),
        migrations.AddField(
            model_name='tasktypetransition',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='recsys.tasktype'),
        ),
        migrations.AddField(
            model_name='tasktypetransition',
            name='target_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_transitions', to='recsys.examversion'),
        ),
        migrations.AddField(
            model_name='tasktypetransition',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='recsys.tasktype'),
        ),
        migrations.AddConstraint(
            model_name='examprogresssnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'exam_version', 'purpose', 'as_of'), name='exam_progress_snapshot_unique'),
        ),
        migrations.AddIndex(
            model_name='taskplacement',
            index=models.Index(fields=['task_type', 'status'], name='placement_type_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskplacement',
            constraint=models.UniqueConstraint(fields=('task', 'task_type'), name='task_placement_unique'),
        ),
        migrations.AddConstraint(
            model_name='tasktypetransition',
            constraint=models.UniqueConstraint(fields=('target_exam', 'source_type', 'target_type'), name='type_transition_unique'),
        ),
    ]
