# Generated by Django 5.2.9 on 2026-09-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0043_examprogresssnapshot_taskplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='variant_task_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='recsys.varianttaskattempt'),
        ),
    ]
