# Generated by Django 5.2.9 on 2026-09-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0044_alter_attempt_variant_task_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationlog',
            name='task_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
