# Generated by Django 5.2.9 on 2026-09-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0045_recommendationlog_task_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianttaskattempt',
            name='submission_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
