# Generated by Django 5.2.9 on 2026-09-12 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0046_varianttaskattempt_submission_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varianttaskattempt',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_task_attempts', to='recsys.task'),
        ),
        migrations.AlterField(
            model_name='varianttaskattempt',
            name='variant_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_attempts', to='recsys.varianttask'),
        ),
    ]
