# Generated by Django 5.2.9 on 2026-09-12 07:17

import apps.recsys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0047_alter_varianttaskattempt_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.recsys.models.task_image_upload_to),
        ),
    ]
