# Generated by Django 5.2.9 on 2026-09-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0048_alter_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktypetransition',
            name='allow_empty_source_pool',
            field=models.BooleanField(default=False, help_text='Для частичного соответствия: намеренно не переносить старые задачи. Укажите причину в примечании.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='scoring_scheme',
            field=models.CharField(blank=True, choices=[('binary', 'Binary (0/1)'), ('partial_pairs', 'Partial pairs (0-2)'), ('ege_pairs_2027', 'ЕГЭ 2027: пара чисел, перестановка — 1 балл'), ('partial_rows', 'Partial rows (0-2)'), ('manual_scaled', 'Manual scaled')], help_text='Optional override of task-type scoring scheme.', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='taskplacement',
            name='scoring_scheme',
            field=models.CharField(blank=True, choices=[('binary', 'Binary (0/1)'), ('partial_pairs', 'Partial pairs (0-2)'), ('ege_pairs_2027', 'ЕГЭ 2027: пара чисел, перестановка — 1 балл'), ('partial_rows', 'Partial rows (0-2)'), ('manual_scaled', 'Manual scaled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='scoring_scheme',
            field=models.CharField(choices=[('binary', 'Binary (0/1)'), ('partial_pairs', 'Partial pairs (0-2)'), ('ege_pairs_2027', 'ЕГЭ 2027: пара чисел, перестановка — 1 балл'), ('partial_rows', 'Partial rows (0-2)'), ('manual_scaled', 'Manual scaled')], default='binary', help_text='How to award points for answers of this task type.', max_length=32),
        ),
    ]
