# Generated by Django 5.2.9 on 2026-08-28 09:47

import accounts.models
import django.core.validators
import django.db.models.deletion
import lessons.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_userpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekdays', models.JSONField(default=list, validators=[lessons.models.validate_weekdays])),
                ('local_time', models.TimeField()),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=64, validators=[accounts.models.validate_timezone_name])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('paused', 'Приостановлена'), ('ended', 'Завершена')], default='active', max_length=16)),
                ('generation_horizon_weeks', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('generated_through', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_series_created', to=settings.AUTH_USER_MODEL)),
                ('teacher_student_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_series', to='accounts.teacherstudentlink')),
            ],
            options={
                'ordering': ['start_date', 'local_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_start', models.DateTimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Проведен'), ('cancelled', 'Отменен'), ('no_show', 'Неявка')], default='scheduled', max_length=16)),
                ('price_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('teacher_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_created', to=settings.AUTH_USER_MODEL)),
                ('teacher_student_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='accounts.teacherstudentlink')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='lessons.lessonseries')),
            ],
            options={
                'ordering': ['scheduled_start', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Создан'), ('reschedule_requested', 'Запрошен перенос'), ('reschedule_accepted', 'Перенос принят'), ('reschedule_rejected', 'Перенос отклонен'), ('completed', 'Проведен'), ('cancelled', 'Отменен'), ('no_show', 'Неявка'), ('payment_paid', 'Оплата получена'), ('payment_refunded', 'Оплата возвращена')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_events', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lessons.lesson')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['lesson', 'created_at'], name='lessons_les_lesson__cf0a5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('unpaid', 'Не оплачен'), ('paid', 'Оплачен'), ('refunded', 'Возвращен')], default='unpaid', max_length=16)),
                ('method', models.CharField(blank=True, choices=[('bank_transfer', 'Перевод'), ('cash', 'Наличные'), ('online', 'Онлайн'), ('other', 'Другое')], max_length=24)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('note', models.TextField(blank=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='lessons.lesson')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='lesson_payment_amount_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='LessonRescheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_start', models.DateTimeField()),
                ('proposed_start', models.DateTimeField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('accepted', 'Принят'), ('rejected', 'Отклонен'), ('cancelled', 'Отозван')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_requests', to='lessons.lesson')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_reschedule_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lesson', 'status'], name='lessons_les_lesson__d54c49_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('lesson',), name='lesson_one_pending_reschedule')],
            },
        ),
        migrations.AddIndex(
            model_name='lessonseries',
            index=models.Index(fields=['status', 'start_date'], name='lessons_les_status_c33c80_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonseries',
            index=models.Index(fields=['teacher_student_link', 'status'], name='lessons_les_teacher_8ee3cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonseries',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='lesson_series_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='lessonseries',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='lesson_series_dates_valid'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['scheduled_start', 'status'], name='lessons_les_schedul_c2f3ab_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['teacher_student_link', 'scheduled_start'], name='lessons_les_teacher_09ef8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.CheckConstraint(condition=models.Q(('price_amount__gte', 0)), name='lesson_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(condition=models.Q(('series__isnull', False)), fields=('series', 'scheduled_start'), name='lesson_series_start_unique'),
        ),
    ]
