# Generated by Django 5.2.9 on 2026-09-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_manual_lesson_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланирован'), ('completed', 'Проведен'), ('cancelled', 'Отменен'), ('no_show', 'Неявка'), ('deleted', 'Удалён как ошибочный')], default='scheduled', max_length=16),
        ),
        migrations.AlterField(
            model_name='lessonevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Создан'), ('reschedule_requested', 'Запрошен перенос'), ('reschedule_accepted', 'Перенос принят'), ('reschedule_rejected', 'Перенос отклонен'), ('completed', 'Проведен'), ('cancelled', 'Отменен'), ('no_show', 'Неявка'), ('payment_paid', 'Оплата получена'), ('payment_refunded', 'Оплата возвращена'), ('rescheduled', 'Перенесён учителем'), ('reopened', 'Отметка проведения отменена'), ('payment_unpaid', 'Отметка оплаты отменена'), ('deleted', 'Ошибочный урок удалён')], max_length=32),
        ),
    ]
